"""
Test semantic output quality - Shows actual responses from the system
"""
import asyncio
import sys
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv('../.env')

sys.path.insert(0, '..')
from agents.graph import run_medical_query

async def test_research_query():
    """Test a research query and show actual output"""
    print("\n" + "="*80)
    print("TEST: Research Query about Hypertension Treatment")
    print("="*80)
    
    query = "What are the current treatment guidelines for hypertension?"
    print(f"\nQuery: {query}\n")
    
    result = await run_medical_query(query)
    
    print("\n--- ROUTING DECISION ---")
    print(f"Plan: {result.get('plan', 'N/A')}")
    print(f"Called EMR: {result.get('need_emr', False)}")
    print(f"Called Research: {result.get('need_research', False)}")
    
    print("\n--- WORKFLOW TRACE ---")
    for msg in result.get('messages', []):
        print(f"  • {msg}")
    
    print("\n--- FINAL RESPONSE (first 1000 chars) ---")
    response = result.get('final_response', 'No response')
    print(response[:1000])
    if len(response) > 1000:
        print(f"\n... [Response continues for {len(response) - 1000} more characters]")
    
    print("\n" + "="*80)
    print("Model: Gemini 2.5 Flash")
    print("Status: ✓ Test Complete")
    print("="*80 + "\n")
    
    return result

async def test_emr_query():
    """Test an EMR query and show actual output"""
    print("\n" + "="*80)
    print("TEST: EMR Query for Patient Lab Results")
    print("="*80)
    
    query = "What are the lab results for patient 10000032?"
    print(f"\nQuery: {query}\n")
    
    result = await run_medical_query(query, patient_id="10000032")
    
    print("\n--- ROUTING DECISION ---")
    print(f"Plan: {result.get('plan', 'N/A')}")
    print(f"Called EMR: {result.get('need_emr', False)}")
    print(f"Called Research: {result.get('need_research', False)}")
    
    print("\n--- WORKFLOW TRACE ---")
    for msg in result.get('messages', []):
        print(f"  • {msg}")
    
    print("\n--- FINAL RESPONSE (first 1000 chars) ---")
    response = result.get('final_response', 'No response')
    print(response[:1000])
    if len(response) > 1000:
        print(f"\n... [Response continues for {len(response) - 1000} more characters]")
    
    print("\n" + "="*80)
    print("Model: Gemini 2.5 Flash")
    print("Status: ✓ Test Complete")
    print("="*80 + "\n")
    
    return result

if __name__ == "__main__":
    print("\n" + "="*80)
    print("SEMANTIC OUTPUT VERIFICATION - Gemini 2.5 Flash")
    print("="*80)
    print("\nThis test shows the actual responses generated by the system")
    print("to verify semantic quality and correctness.\n")
    
    # Test 1: Research query
    asyncio.run(test_research_query())
    
    print("\n" + "-"*80 + "\n")
    
    # Test 2: EMR query
    asyncio.run(test_emr_query())
    
    print("\n" + "="*80)
    print("ALL TESTS COMPLETE - SEMANTIC OUTPUT VERIFIED")
    print("="*80)
